'use client';
import { useEffect, useMemo, useState } from 'react';
import { CalendarRange, CheckCircle2, Clock3, Plus, Save, Sparkles, UserCog, UsersRound } from 'lucide-react';
import AppShell from '@/components/AppShell';
import { EmptyState, LoadingState, StatusPill } from '@/components/AdminUi';
import { apiFetch } from '@/lib/client-api';

const days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const fallbackAreas=[{key:'front-desk',label:'Front desk'},{key:'studios',label:'Studios'},{key:'woods',label:'Woods'},{key:'metals',label:'Metals'},{key:'design',label:'Design'},{key:'textiles',label:'Textiles'},{key:'techlab',label:'TechLab'}];
const fallbackRoles=[{key:'student-technician',label:'Student technician'},{key:'technician',label:'Technician'},{key:'mentor',label:'Mentor'},{key:'manager',label:'Manager'}];
function isoDate(date){return date.toISOString().slice(0,10)}
function monday(){const d=new Date();d.setHours(0,0,0,0);const day=d.getDay();d.setDate(d.getDate()+(day===0?1:1-day));return d}
function shiftStyle(s){const a=new Date(s.startsAt),b=new Date(s.endsAt),start=a.getHours()*60+a.getMinutes(),end=b.getHours()*60+b.getMinutes(),base=9*60,span=12*60;return{marginLeft:`${Math.max(0,(start-base)/span*100)}%`,width:`${Math.max(12,(end-start)/span*100)}%`}}

export default function SchedulePage(){
 const initial=monday();
 const [start,setStart]=useState(isoDate(initial)); const [end,setEnd]=useState(isoDate(new Date(initial.getTime()+6*86400000)));
 const [data,setData]=useState(null); const [selected,setSelected]=useState(null); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
 const [staff,setStaff]=useState({displayName:'',email:'',staffRole:'student-technician',primaryArea:'front-desk'});
 async function load(){const r=await apiFetch(`/api/schedule?start=${start}&end=${end}`,{cache:'no-store'});const x=await r.json();if(r.ok)setData(x);else setMessage(x.error)}
 useEffect(()=>{load()},[start,end]);
 async function generate(){setBusy(true);setMessage('Building a balanced, repeatable schedule…');const r=await apiFetch('/api/schedule',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({start,end})});const x=await r.json();setBusy(false);if(r.ok){setData({...data,shifts:x.shifts});setMessage(`Generated ${x.assignments.length} assignments with ${x.warnings.length} coverage warning${x.warnings.length===1?'':'s'}.`)}else setMessage(x.error)}
 async function publish(){const r=await apiFetch('/api/schedule',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({status:'published',periodId:`${start}_${end}`,shifts:data.shifts})});setMessage(r.ok?'Schedule published and ready for employee acknowledgments.':(await r.json()).error);if(r.ok)load()}
 async function createStaff(){const r=await apiFetch('/api/staff',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(staff)});const x=await r.json();if(r.ok){setMessage(`${x.person.displayName} added to staff scheduling.`);setStaff({displayName:'',email:'',staffRole:'student-technician',primaryArea:'front-desk'});load()}else setMessage(x.error)}
 async function saveAvailability(){if(!selected)return;const entries=days.map((_,day)=>selected.availability?.[day]).filter(Boolean).map((v)=>({...v,employeeId:selected.id}));const r=await apiFetch('/api/staff',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({employeeId:selected.id,availability:entries})});setMessage(r.ok?'Availability saved.':(await r.json()).error);if(r.ok)load()}
 function choose(person){const rows={};for(const item of data.availability.filter(v=>v.employeeId===person.id))rows[item.dayOfWeek]={...item};setSelected({...person,availability:rows})}
 const shiftsByDay=useMemo(()=>{const out={};for(const shift of data?.shifts||[]){const key=new Date(shift.startsAt).toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'});(out[key] ||= []).push(shift)}return out},[data]);
 const areaOptions=data?.settings?.areas?.length?data.settings.areas:fallbackAreas; const roleOptions=data?.settings?.staffRoles?.length?data.settings.staffRoles:fallbackRoles;
 return <AppShell title="Staff scheduling" subtitle="Availability, stable assignments, technician coverage, overlap, mentors, and publishing" actions={<><button className="btn secondary" onClick={load}><CalendarRange size={18}/>Refresh</button><button className="btn primary" onClick={generate} disabled={busy}><Sparkles size={18}/>{busy?'Generating…':'Generate schedule'}</button></>}>
  {message&&<div className={`inline-alert ${message.includes('saved')||message.includes('published')||message.includes('Generated')||message.includes('added')?'success':'error'}`}>{message}</div>}
  {!data?<LoadingState/>:<>
   <section className="schedule-toolbar panel"><label><span>Period starts</span><input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label><span>Period ends</span><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><div><span>Publishing cadence</span><strong>{data.settings.publishCadence}</strong></div><div><span>Shift overlap</span><strong>{data.settings.overlapMinutes} minutes</strong></div><button className="btn secondary" disabled={!data.shifts.length} onClick={publish}><CheckCircle2 size={18}/>Publish</button></section>
   <section className="schedule-layout"><article className="panel schedule-board"><div className="section-heading"><div><p className="eyebrow">Draft and published shifts</p><h2>Coverage board</h2></div><StatusPill tone={data.shifts.some(s=>s.status==='published')?'green':'yellow'}>{data.shifts.length} assignments</StatusPill></div>{!data.shifts.length?<EmptyState icon={CalendarRange} title="No schedule generated" message="Collect employee availability, then generate a stable schedule."/>:<div className="schedule-days">{Object.entries(shiftsByDay).map(([day,shifts])=><section key={day}><h3>{day}</h3><div className="shift-axis"><span>9a</span><span>12p</span><span>3p</span><span>6p</span><span>9p</span></div>{shifts.map(s=><div className="shift-track" key={s.id}><article className="shift-block" style={shiftStyle(s)}><span className="avatar-initial">{s.employeeName?.[0]||'?'}</span><div><strong>{s.employeeName}</strong><small>{new Date(s.startsAt).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}–{new Date(s.endsAt).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</small></div><StatusPill tone={s.status==='published'?'green':'blue'}>{s.roleKey}</StatusPill></article></div>)}</section>)}</div>}</article>
    <aside className="schedule-side"><article className="panel card-section"><div className="section-heading"><div><p className="eyebrow">Staff directory</p><h2>Availability</h2></div><UsersRound/></div><div className="compact-people-list">{data.employees.map(p=><button key={p.id} className={selected?.id===p.id?'selected':''} onClick={()=>choose(p)}><span className="avatar-initial">{p.displayName?.[0]}</span><span><strong>{p.displayName}</strong><small>{p.staffRole||'student technician'} · {p.primaryArea||'front desk'}</small></span></button>)}</div></article>
    {selected&&<article className="panel card-section availability-editor"><h2>{selected.displayName}</h2><p className="muted-block">Set recurring availability. Closing staff overlap the next shift according to the scheduling setting.</p>{days.map((label,day)=>{const v=selected.availability?.[day];return <div className="availability-row" key={label}><label><input type="checkbox" checked={Boolean(v)} onChange={e=>setSelected(curr=>({...curr,availability:{...curr.availability,[day]:e.target.checked?{dayOfWeek:day,startsTime:day===0?'13:00':'09:00',endsTime:day===0?'18:00':'21:00',availabilityType:'available'}:undefined}}))}/>{label}</label>{v&&<><input type="time" value={v.startsTime} onChange={e=>setSelected(curr=>({...curr,availability:{...curr.availability,[day]:{...curr.availability[day],startsTime:e.target.value}}}))}/><input type="time" value={v.endsTime} onChange={e=>setSelected(curr=>({...curr,availability:{...curr.availability,[day]:{...curr.availability[day],endsTime:e.target.value}}}))}/></>}</div>})}<button className="btn primary wide" onClick={saveAvailability}><Save size={18}/>Save availability</button></article>}
    <article className="panel card-section"><div className="section-heading"><div><p className="eyebrow">Manual staff</p><h2>Add mentor or employee</h2></div><UserCog/></div><div className="field-grid one"><label className="field"><span>Name</span><input value={staff.displayName} onChange={e=>setStaff({...staff,displayName:e.target.value})}/></label><label className="field"><span>Email</span><input type="email" value={staff.email} onChange={e=>setStaff({...staff,email:e.target.value})}/></label><label className="field"><span>Role</span><select value={staff.staffRole} onChange={e=>setStaff({...staff,staffRole:e.target.value})}>{roleOptions.map(v=><option key={v.key} value={v.key}>{v.label}</option>)}</select></label><label className="field"><span>Primary area</span><select value={staff.primaryArea} onChange={e=>setStaff({...staff,primaryArea:e.target.value})}>{areaOptions.map(v=><option key={v.key} value={v.key}>{v.label}</option>)}</select></label></div><button className="btn secondary wide" disabled={!staff.displayName} onClick={createStaff}><Plus size={18}/>Add to staff</button></article></aside>
   </section>
  </>}
 </AppShell>
}
