'use client';
import {
  ArrowDown, BadgeCheck, BriefcaseBusiness, Building2, Check, ChevronLeft, CircleHelp,
  Clock3, Delete, GraduationCap, IdCard, Keyboard, LayoutDashboard, LogIn, LogOut,
  QrCode, Radio, RefreshCw, Search, ShieldAlert, Smartphone, UserPlus, UsersRound, X,
} from 'lucide-react';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import DateOfBirthPicker from '@/components/DateOfBirthPicker';
import { apiFetch, assetUrl, setClientAdminToken } from '@/lib/client-api';
import { cleanBadge, formatDate } from '@/lib/utils';

const KIOSK_ID = process.env.NEXT_PUBLIC_KIOSK_ID || 'front-door';
const KIOSK_LABEL = process.env.NEXT_PUBLIC_KIOSK_LABEL || 'Front Desk';
const fallbackConfig = {
  kiosk: { resultTimeoutSeconds: 5, formTimeoutSeconds: 90, claimTimeoutSeconds: 600, helpTimeoutSeconds: 60, showClock: true, showScannerArrow: true, scannerInstruction: 'Hold your badge over the reader below — not against the screen.' },
  guests: { requireDateOfBirth: false, requirePhone: false, waiverRequired: true, waiverText: 'GoCreate contains tools, equipment, materials, and activities that may involve risk. The guest agrees to follow all staff instructions and posted rules, accepts responsibility for their conduct and personal property, and acknowledges that GoCreate is not responsible for injury, loss, or damage to the fullest extent allowed by law. Guests may not use tools or machines unless separately authorized by GoCreate staff.' },
};

function emptyGuestForm(){return{firstName:'',lastName:'',dob:'',phone:'',waiverAccepted:false,initials:''}}
function ActionCard({icon:Icon,title,description,tone='blue',onClick,disabled}){return <button className={`kiosk-action ${tone}`} onClick={onClick} disabled={disabled}><span className="kiosk-action-icon"><Icon/></span><span><strong>{title}</strong><small>{description}</small></span></button>}
function SafePhoto({src,name}){const[failing,setFailing]=useState(false);if(!src||failing)return <span className="profile-photo-fallback">{String(name||'?').split(/\s+/).slice(0,2).map(v=>v[0]).join('').toUpperCase()}</span>;return <img src={assetUrl(src)} alt={name||'Badge holder'} onError={()=>setFailing(true)}/>}
function localClock(date){return date.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}
function localDate(date){return date.toLocaleDateString([],{weekday:'long',month:'long',day:'numeric',year:'numeric'})}

export default function Kiosk(){
 const[mode,setMode]=useState('idle');const[scanCode,setScanCode]=useState('');const[data,setData]=useState(null);const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);const[help,setHelp]=useState(false);
 const[guestForm,setGuestForm]=useState(emptyGuestForm());const[linkQuery,setLinkQuery]=useState('');const[linkResults,setLinkResults]=useState([]);const[linkPerson,setLinkPerson]=useState(null);const[verification,setVerification]=useState('');const[affiliation,setAffiliation]=useState('unspecified');const[config,setConfig]=useState(fallbackConfig);const[now,setNow]=useState(new Date());const[secondsRemaining,setSecondsRemaining]=useState(null);const[viewportHeight,setViewportHeight]=useState(null);
 const buffer=useRef('');const scanTimer=useRef(null);const resetTimer=useRef(null);const searchTimer=useRef(null);const helpTimer=useRef(null);const inactivityDeadline=useRef(0);const acknowledgedCommand=useRef(0);const lastInteractionAt=useRef(new Date().toISOString());
 const claimId=data?.claimId||'';
 const modeTimeout=useCallback((name)=>{if(name==='idle'||name==='success')return 0;if(name==='processing')return 25;if(name==='membership')return Math.max(60,Number(config.kiosk.formTimeoutSeconds||90));if(name==='help')return Number(config.kiosk.helpTimeoutSeconds||60);return Math.max(30,Number(config.kiosk.formTimeoutSeconds||90))},[config]);
 const logKiosk=useCallback((action,details={})=>{apiFetch('/api/audit',{method:'POST',keepalive:true,headers:{'content-type':'application/json'},body:JSON.stringify({action,source:'kiosk-ui',targetType:'kiosk',targetId:KIOSK_ID,kioskId:KIOSK_ID,details})}).catch(()=>{})},[]);
 const reset=useCallback((reason='manual')=>{clearTimeout(resetTimer.current);clearTimeout(searchTimer.current);clearTimeout(helpTimer.current);buffer.current='';inactivityDeadline.current=0;setMode('idle');setScanCode('');setData(null);setMessage('');setBusy(false);setHelp(false);setGuestForm(emptyGuestForm());setLinkQuery('');setLinkResults([]);setLinkPerson(null);setVerification('');setAffiliation('unspecified');setSecondsRemaining(null);if(reason!=='silent')logKiosk('kiosk.reset',{reason})},[logKiosk]);
 const changeMode=useCallback((next,details={})=>{setMode(next);const seconds=modeTimeout(next);inactivityDeadline.current=seconds?Date.now()+seconds*1000:0;setSecondsRemaining(seconds||null);lastInteractionAt.current=new Date().toISOString();logKiosk('kiosk.screen.opened',{mode:next,...details})},[logKiosk,modeTimeout]);
 const touch=useCallback(()=>{lastInteractionAt.current=new Date().toISOString();const seconds=modeTimeout(mode);if(seconds)inactivityDeadline.current=Date.now()+seconds*1000},[mode,modeTimeout]);
 const showSuccess=useCallback((text)=>{setMessage(text);setMode('success');inactivityDeadline.current=0;setSecondsRemaining(null);const ms=Math.max(2000,Number(config.kiosk.resultTimeoutSeconds||5)*1000);resetTimer.current=setTimeout(()=>reset('completed'),ms)},[config,reset]);

 useEffect(()=>{apiFetch('/api/kiosk/config',{cache:'no-store'}).then(r=>r.json()).then(x=>x.ok&&setConfig(x)).catch(()=>{})},[]);
 useEffect(()=>{const t=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(t)},[]);
 useEffect(()=>{const vv=window.visualViewport;if(!vv)return;const update=()=>setViewportHeight(vv.height);update();vv.addEventListener('resize',update);return()=>vv.removeEventListener('resize',update)},[]);
 useEffect(()=>{const timer=setInterval(()=>{if(!inactivityDeadline.current||help||mode==='idle'||mode==='success')return;const remaining=Math.max(0,Math.ceil((inactivityDeadline.current-Date.now())/1000));setSecondsRemaining(remaining);if(!remaining){logKiosk('kiosk.timeout',{mode});reset('inactivity-timeout')}},1000);return()=>clearInterval(timer)},[help,mode,reset,logKiosk]);
 useEffect(()=>{const activity=()=>touch();window.addEventListener('pointerdown',activity,{passive:true});window.addEventListener('input',activity,true);return()=>{window.removeEventListener('pointerdown',activity);window.removeEventListener('input',activity,true)}},[touch]);

 useEffect(()=>{async function heartbeat(){try{const r=await apiFetch('/api/kiosks',{method:'POST',signal:AbortSignal.timeout(3500),headers:{'content-type':'application/json'},body:JSON.stringify({action:'heartbeat',kioskId:KIOSK_ID,label:KIOSK_LABEL,mode,route:window.location.pathname,acknowledgedVersion:acknowledgedCommand.current,screenVersion:'6.2.0',lastInteractionAt:lastInteractionAt.current})});const x=await r.json();const command=x.command;if(!command||Number(command.version)<=acknowledgedCommand.current)return;acknowledgedCommand.current=Number(command.version);if(command.name==='reset')reset('remote-admin');else if(command.name==='reload')window.location.reload();else if(command.name==='show-membership')changeMode('membership',{source:'remote-admin'});else if(command.name==='navigate-kiosk')window.location.href='/kiosk'}catch{}}heartbeat();const t=setInterval(heartbeat,4000);return()=>clearInterval(t)},[mode,reset,changeMode]);

 const submitScan=useCallback(async(raw)=>{const badgeNumber=cleanBadge(raw);buffer.current='';clearTimeout(scanTimer.current);if(!badgeNumber||busy)return;setScanCode(badgeNumber);changeMode('processing');setBusy(true);setMessage('');try{const r=await apiFetch('/api/scan',{method:'POST',signal:AbortSignal.timeout(15000),headers:{'content-type':'application/json'},body:JSON.stringify({badgeNumber,kioskId:KIOSK_ID})});const x=await r.json();if(!r.ok){if(x.code==='BADGE_UNKNOWN'){setData(x);changeMode('unknown',{badgeNumber,claimId:x.claimId});return}throw new Error(x.error||'The badge could not be read.')}setData(x);changeMode('profile',{personId:x.person?.id})}catch(error){setMessage(error.name==='TimeoutError'?'The kiosk server took too long. Please try again.':error.message);changeMode('error')}finally{setBusy(false)}},[busy,changeMode]);
 useEffect(()=>{function key(event){touch();if(help)return;const tag=document.activeElement?.tagName?.toLowerCase();if(['input','textarea','select'].includes(tag)&&mode!=='manual-entry')return;if(mode==='manual-entry'){if(/^\d$/.test(event.key)){event.preventDefault();setScanCode(v=>cleanBadge(v+event.key).slice(0,40))}else if(['Backspace','Delete'].includes(event.key)){event.preventDefault();setScanCode(v=>v.slice(0,-1))}else if(event.key==='Enter'&&scanCode){event.preventDefault();submitScan(scanCode)}return}if(event.key==='Enter'||event.key==='Tab'){event.preventDefault();if(buffer.current)submitScan(buffer.current);return}if(event.key.length!==1)return;event.preventDefault();buffer.current+=event.key;setScanCode(cleanBadge(buffer.current));clearTimeout(scanTimer.current);scanTimer.current=setTimeout(()=>{if(cleanBadge(buffer.current).length>=3)submitScan(buffer.current)},140)}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[help,mode,scanCode,submitScan,touch]);

 async function act(action,extra={}){if(!data?.person?.id||busy)return;setBusy(true);try{const r=await apiFetch('/api/attendance',{method:'POST',signal:AbortSignal.timeout(15000),headers:{'content-type':'application/json'},body:JSON.stringify({personId:data.person.id,action,kioskId:KIOSK_ID,...extra})});const x=await r.json();if(!r.ok)throw new Error(x.error);showSuccess(x.message)}catch(error){setMessage(error.message||'That action could not be completed.');changeMode('error')}finally{setBusy(false)}}
 async function openAdmin(){setBusy(true);try{const r=await apiFetch('/api/admin/session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({challenge:data.adminChallenge})});const x=await r.json();if(!r.ok)throw new Error(x.error);setClientAdminToken(x.token||'');window.location.href=x.redirect||'/admin'}catch(error){setMessage(error.message);changeMode('error');setBusy(false)}}
 async function searchLinkable(term=linkQuery){const q=String(term||'').trim();if(q.length<2){setLinkResults([]);return}setBusy(true);try{const r=await apiFetch(`/api/kiosk/linkable-people?q=${encodeURIComponent(q)}`,{signal:AbortSignal.timeout(10000)});const x=await r.json();setLinkResults(x.people||[])}catch(error){setMessage(error.message)}finally{setBusy(false)}}
 async function refreshDirectory(){setBusy(true);try{const r=await apiFetch('/api/kiosk/refresh-directory',{method:'POST',signal:AbortSignal.timeout(10000)});const x=await r.json();setMessage(r.ok?(x.message||'Directory refresh requested.'):x.error)}finally{setBusy(false)}}
 async function linkBadge(){const personId=linkPerson?.id;const code=String(verification).replace(/\D/g,'').slice(-4);if(!personId||code.length!==4)return;setBusy(true);setMessage('');try{const r=await apiFetch('/api/kiosk/link-badge',{method:'POST',signal:AbortSignal.timeout(15000),headers:{'content-type':'application/json'},body:JSON.stringify({claimId,badgeNumber:scanCode,personId,verification:code,affiliation,kioskId:KIOSK_ID})});const x=await r.json();if(!r.ok)throw new Error(x.error);setMessage(x.message);setMode('success');resetTimer.current=setTimeout(()=>submitScan(scanCode),1300)}catch(error){setMessage(error.name==='TimeoutError'?'Badge linking timed out. Please ask the front desk.':error.message)}finally{setBusy(false)}}
 function chooseAffiliation(value){setAffiliation(value);changeMode('link-verify',{affiliation:value})}
 function openHelp(){setHelp(true);clearTimeout(helpTimer.current);helpTimer.current=setTimeout(()=>setHelp(false),Math.max(30,Number(config.kiosk.helpTimeoutSeconds||60))*1000)}
 const memberAllowed=data?.membership?.memberCheckInAllowed;const inside=Boolean(data?.presence?.inside);const employeeCanGuest=Boolean(data?.person?.isEmployee&&data?.openShift);const timeoutVisible=secondsRemaining!==null&&secondsRemaining<=10&&secondsRemaining>0&&mode!=='success';

 return <main className="public-kiosk" style={viewportHeight?{'--visual-height':`${viewportHeight}px`}:undefined}>
  <header className="kiosk-header"><div className="kiosk-brand"><img src="/GCVertical_ColorAndBlack.svg" alt="GoCreate"/><div><strong>Member Check-In</strong><span>{KIOSK_LABEL}</span></div></div>{config.kiosk.showClock&&<div className="kiosk-clock"><strong>{localClock(now)}</strong><span>{localDate(now)}</span></div>}<div className="kiosk-header-actions"><button className="kiosk-help" onClick={()=>changeMode('membership')}><QrCode/>Membership</button><button className="kiosk-help" onClick={openHelp}><CircleHelp/>Help</button></div></header>
  {timeoutVisible&&<div className="kiosk-timeout-banner">Returning to scanner in {secondsRemaining} seconds</div>}
  <section className="kiosk-stage" aria-live="polite">
   {mode==='idle'&&<div className="kiosk-idle scene-enter"><div className="scan-orbit"><span/><div><IdCard/></div></div><p className="eyebrow">Scanner ready</p><h1>Hold your badge over the reader below</h1><p className="kiosk-lead">{config.kiosk.scannerInstruction}</p>{config.kiosk.showScannerArrow&&<div className="physical-reader-cue"><ArrowDown/><strong>RFID reader</strong><span>bottom center of this monitor</span></div>}<div className="reader-passive-status"><span/><Radio/>Ready for a badge</div><div className="idle-secondary-actions"><button className="manual-badge-button" onClick={()=>{setScanCode('');changeMode('manual-entry')}}><Keyboard/>Enter badge number</button><button className="manual-badge-button membership-button" onClick={()=>changeMode('membership')}><QrCode/>Become a member</button></div></div>}
   {mode==='manual-entry'&&<div className="kiosk-flow manual-badge-flow scene-enter"><button className="back-button" onClick={()=>reset('back')}><ChevronLeft/>Back</button><div className="flow-icon blue"><Keyboard/></div><p className="eyebrow">Manual badge entry</p><h1>Enter your badge number</h1><div className="manual-badge-display">{scanCode||<span>Badge number</span>}</div><div className="numeric-keypad">{[1,2,3,4,5,6,7,8,9].map(d=><button key={d} onClick={()=>setScanCode(v=>cleanBadge(v+d).slice(0,40))}>{d}</button>)}<button className="keypad-secondary" onClick={()=>setScanCode('')}>Clear</button><button onClick={()=>setScanCode(v=>cleanBadge(v+'0').slice(0,40))}>0</button><button className="keypad-secondary" onClick={()=>setScanCode(v=>v.slice(0,-1))}><Delete/></button></div><button className="btn primary kiosk-confirm" disabled={!scanCode||busy} onClick={()=>submitScan(scanCode)}><LogIn/>Continue</button></div>}
   {mode==='processing'&&<div className="kiosk-processing scene-enter"><div className="processing-ring"><BadgeCheck/></div><h1>Reading your badge…</h1><p>{scanCode}</p></div>}
   {mode==='unknown'&&<div className="kiosk-flow scene-enter"><div className="flow-icon amber"><IdCard/></div><p className="eyebrow">First-time badge</p><h1>Link this badge to your account</h1><p className="kiosk-lead">The badge is safely held in a temporary link session, so this page can refresh without losing it.</p><div className="large-actions"><ActionCard icon={UserPlus} title="Find my account" description="Search GoCreate users and memberships" onClick={()=>changeMode('link-search')}/><ActionCard icon={CircleHelp} title="Ask the front desk" description="Use this when no account exists" tone="neutral" onClick={()=>changeMode('frontdesk')}/></div><button className="text-button" onClick={()=>reset('cancel')}><X/>Cancel</button></div>}
   {mode==='link-search'&&<div className="kiosk-flow kiosk-link scene-enter"><button className="back-button" onClick={()=>changeMode('unknown')}><ChevronLeft/>Back</button><p className="eyebrow">Badge {scanCode}</p><h1>Find your GoCreate account</h1><p className="kiosk-lead">Search by name or email. Results update while you type.</p><div className="kiosk-search"><Search/><input autoFocus value={linkQuery} onChange={e=>{const next=e.target.value;setLinkQuery(next);clearTimeout(searchTimer.current);if(next.trim().length>=2)searchTimer.current=setTimeout(()=>searchLinkable(next),200);else setLinkResults([])}} placeholder="Start typing your name or email"/><button onClick={()=>searchLinkable()} disabled={busy||linkQuery.trim().length<2}>Search</button></div><div className="kiosk-results">{linkResults.map(p=><button key={p.id} onClick={()=>{setLinkPerson(p);changeMode('link-student')}}><span className="avatar-initial">{p.displayName?.[0]||'?'}</span><span><strong>{p.displayName}</strong><small>{p.isEmployee?'Employee account':p.membershipStatus}</small></span><ChevronLeft className="result-arrow"/></button>)}{!busy&&linkQuery.trim().length>=2&&!linkResults.length&&<div className="friendly-empty"><UsersRound/><strong>No account matched</strong><p>Try email or another spelling. This page returns to the scanner automatically.</p><button className="refresh-directory-button" onClick={refreshDirectory}><RefreshCw/>Refresh user list</button><button className="refresh-directory-button secondary" onClick={()=>changeMode('membership')}><QrCode/>Create a membership</button>{message&&<small>{message}</small>}</div>}</div></div>}
   {mode==='link-student'&&<div className="kiosk-flow scene-enter"><button className="back-button" onClick={()=>changeMode('link-search')}><ChevronLeft/>Back</button><div className="flow-icon blue"><GraduationCap/></div><p className="eyebrow">Account details</p><h1>Are you currently a student?</h1><p className="kiosk-lead">This helps the front desk keep the right affiliation on your account.</p><div className="large-actions"><ActionCard icon={GraduationCap} title="Yes" description="Choose Wichita State or WSU Tech next" onClick={()=>changeMode('link-school')}/><ActionCard icon={UserPlus} title="No" description="Continue without a student affiliation" tone="neutral" onClick={()=>chooseAffiliation('none')}/></div></div>}
   {mode==='link-school'&&<div className="kiosk-flow scene-enter"><button className="back-button" onClick={()=>changeMode('link-student')}><ChevronLeft/>Back</button><div className="flow-icon blue"><Building2/></div><p className="eyebrow">Student affiliation</p><h1>Which school?</h1><div className="school-choice"><button onClick={()=>chooseAffiliation('wsu')}><span className="school-mark">WSU</span><strong>Wichita State University</strong></button><button onClick={()=>chooseAffiliation('wsu-tech')}><span className="school-mark tech">TECH</span><strong>WSU Tech</strong></button></div></div>}
   {mode==='link-verify'&&<div className="kiosk-flow scene-enter"><button className="back-button" onClick={()=>changeMode('link-student')}><ChevronLeft/>Back</button><div className="flow-icon blue"><ShieldAlert/></div><p className="eyebrow">Final verification</p><h1>Enter the last four phone digits</h1><p className="kiosk-lead">Use the phone number on <strong>{linkPerson?.displayName}</strong>’s account.</p><input className="verification-input" inputMode="numeric" autoFocus maxLength={4} value={verification} onChange={e=>setVerification(cleanBadge(e.target.value).slice(0,4))} placeholder="••••"/>{message&&<div className="inline-alert error"><ShieldAlert/>{message}</div>}<button className="btn primary kiosk-confirm" onClick={linkBadge} disabled={busy||verification.length!==4}>Link this badge</button></div>}
   {mode==='profile'&&data&&<div className="kiosk-profile scene-enter"><div className="profile-hero"><SafePhoto src={data.badge?.photoUrl||data.person?.photoUrl} name={data.person.displayName}/><div><p className="eyebrow">Badge recognized</p><h1>Hello, {data.person.displayName?.split(' ')[0]}</h1><p>{data.person.displayName}</p></div><span className={`membership-pill ${!memberAllowed?'blocked':data.membership.status==='approved'?'current':'informational'}`}>{data.membership.title}</span></div>{!memberAllowed&&<div className="membership-message"><ShieldAlert/><div><strong>Please see the front desk</strong><p>{data.membership.message}{data.membership.expiresAt?` Expiration: ${formatDate(data.membership.expiresAt)}.`:''} Entry is not recorded until the status is resolved or an authorized temporary override is applied.</p></div></div>}<div className="kiosk-choice-heading"><h2>Choose an action</h2><p>Only actions that apply to this badge are shown.</p></div><div className="large-actions profile-actions">{!inside&&memberAllowed&&<ActionCard icon={LogIn} title="Check in" description="Record my arrival" tone="green" onClick={()=>act('check-in')} disabled={busy}/>} {inside&&<ActionCard icon={LogOut} title="Check out" description="Record that I am leaving" tone="red" onClick={()=>act('check-out')} disabled={busy}/>} {data.person.isEmployee&&!data.openShift&&<ActionCard icon={Clock3} title="Clock in" description="Start my employee shift" tone="yellow" onClick={()=>act('clock-in')} disabled={busy}/>} {data.person.isEmployee&&data.openShift&&<ActionCard icon={BriefcaseBusiness} title="Clock out" description="End my employee shift" tone="yellow" onClick={()=>act('clock-out')} disabled={busy}/>} {(inside||employeeCanGuest)&&<ActionCard icon={UserPlus} title="Check in a guest" description={employeeCanGuest&&!inside?'Register as the on-duty employee':'Register someone visiting'} tone="blue" onClick={()=>changeMode('guest')}/>} {data.openGuests?.length>0&&<ActionCard icon={UsersRound} title="Manage guests" description={`${data.openGuests.length} currently inside`} tone="neutral" onClick={()=>changeMode('guest-list')}/>} {data.person.isAdmin&&<ActionCard icon={LayoutDashboard} title="Admin dashboard" description="Open authorized operations tools" tone="purple" onClick={openAdmin}/>}</div><button className="text-button" onClick={()=>reset('cancel')}><X/>Finish</button></div>}
   {mode==='guest'&&<div className="kiosk-flow guest-waiver-flow scene-enter"><button className="back-button" onClick={()=>changeMode('profile')}><ChevronLeft/>Back</button><p className="eyebrow">Guest check-in</p><h1>Guest information and acknowledgment</h1><div className="guest-form"><label><span>First name</span><input autoFocus value={guestForm.firstName} onChange={e=>setGuestForm({...guestForm,firstName:e.target.value})}/></label><label><span>Last name</span><input value={guestForm.lastName} onChange={e=>setGuestForm({...guestForm,lastName:e.target.value})}/></label>{config.guests.requireDateOfBirth&&<label className="wide"><span>Date of birth</span><DateOfBirthPicker value={guestForm.dob} onChange={dob=>setGuestForm({...guestForm,dob})}/></label>}<label><span>Phone {config.guests.requirePhone?'':'(optional)'}</span><input inputMode="tel" value={guestForm.phone} onChange={e=>setGuestForm({...guestForm,phone:e.target.value})}/></label></div>{config.guests.waiverRequired&&<section className="guest-waiver"><h2>Guest acknowledgment and release</h2><p>{config.guests.waiverText}</p><label className="waiver-check"><input type="checkbox" checked={guestForm.waiverAccepted} onChange={e=>setGuestForm({...guestForm,waiverAccepted:e.target.checked})}/><span>I have read and agree to this guest acknowledgment.</span></label><label><span>Guest initials</span><input className="guest-initials" maxLength={8} value={guestForm.initials} onChange={e=>setGuestForm({...guestForm,initials:e.target.value.toUpperCase().replace(/[^A-Z]/g,'')})}/></label></section>}<button className="btn primary kiosk-confirm" onClick={()=>act('add-guest',guestForm)} disabled={busy||!guestForm.firstName||!guestForm.lastName||(config.guests.requireDateOfBirth&&!guestForm.dob)||(config.guests.requirePhone&&!guestForm.phone)||(config.guests.waiverRequired&&(!guestForm.waiverAccepted||guestForm.initials.length<2))}>Agree and check in guest</button></div>}
   {mode==='guest-list'&&<div className="kiosk-flow scene-enter"><button className="back-button" onClick={()=>changeMode('profile')}><ChevronLeft/>Back</button><p className="eyebrow">Guest presence</p><h1>Check out a guest</h1><div className="guest-list">{data.openGuests.map(g=><button key={g.id} onClick={()=>act('guest-check-out',{visitId:g.id})}><span className="avatar-initial">{g.displayName?.[0]}</span><span><strong>{g.displayName}</strong><small>Checked in {g.checkInAt?localClock(new Date(g.checkInAt)):''}</small></span><LogOut/></button>)}</div></div>}
   {mode==='membership'&&<div className="kiosk-flow membership-qr-flow scene-enter"><button className="back-button" onClick={()=>reset('membership-done')}><ChevronLeft/>Back to scanner</button><div className="flow-icon blue"><QrCode/></div><p className="eyebrow">GoCreate membership</p><h1>Scan to create or renew a membership</h1><div className="membership-qr-card"><img src="/membership-qr.png" alt="QR code for GoCreate membership"/><strong>gocreate.com/membership</strong></div><button className="btn primary kiosk-confirm" onClick={()=>reset('membership-done')}>Done</button></div>}
   {mode==='frontdesk'&&<div className="kiosk-flow scene-enter"><div className="flow-icon blue"><CircleHelp/></div><h1>The front desk can help</h1><p className="kiosk-lead">No account is required to stay on this screen. It will return to the scanner automatically so the next visitor is never blocked.</p><div className="button-row centered"><button className="btn secondary kiosk-confirm" onClick={()=>changeMode('membership')}><QrCode/>Create membership</button><button className="btn primary kiosk-confirm" onClick={()=>reset('frontdesk-done')}>Done</button></div></div>}
   {mode==='success'&&<div className="kiosk-success scene-enter"><div className="success-mark"><Check/></div><h1>All set</h1><p>{message}</p><span>Returning to the scanner…</span></div>}
   {mode==='error'&&<div className="kiosk-flow scene-enter"><div className="flow-icon red"><ShieldAlert/></div><h1>We could not finish that</h1><p className="kiosk-lead">{message}</p><button className="btn primary kiosk-confirm" onClick={()=>reset('error-dismissed')}>Return to scanner</button></div>}
  </section>
  <footer className="kiosk-footer"><span>GoCreate · A Koch Collaborative</span><span>Scans, guest acknowledgments, and changes are logged for operations and safety.</span></footer>
  {help&&<div className="modal-back public-modal" onClick={()=>setHelp(false)}><section className="modal-card" onClick={e=>e.stopPropagation()}><div className="modal-heading"><div className="icon-tile blue"><CircleHelp/></div><div><h2>How to use the kiosk</h2><p>The RFID reader is physically below the monitor.</p></div></div><div className="help-grid"><article><IdCard/><div><strong>Use the reader below</strong><p>Hold the badge over the PCProx Plus reader. Do not place it against the screen.</p></div></article><article><Smartphone/><div><strong>No account found</strong><p>Use the membership QR or ask the front desk. The screen resets on its own.</p></div></article><article><ShieldAlert/><div><strong>Membership needs attention</strong><p>Pending, expired, or inactive accounts follow the policy configured by authorized staff.</p></div></article><article><RefreshCw/><div><strong>Automatic recovery</strong><p>Every form has a timeout, and staff can force a reset from another computer.</p></div></article></div><button className="btn primary wide" onClick={()=>setHelp(false)}>Back</button></section></div>}
 </main>
}
