'use client';
import { useEffect,useState } from 'react';import { Clock3,LogOut,RefreshCw,UserRoundCheck,UsersRound,BriefcaseBusiness,CalendarClock } from 'lucide-react';import AppShell from '@/components/AppShell';import { EmptyState,LoadingState,StatusPill } from '@/components/AdminUi';import { apiFetch } from '@/lib/client-api';import { formatDateTime } from '@/lib/utils';
function elapsed(v){const m=Math.max(0,Math.floor((Date.now()-new Date(v))/60000));return m<60?`${m}m`:`${Math.floor(m/60)}h ${m%60}m`}
export default function PresencePage(){const[data,setData]=useState(null),[message,setMessage]=useState(''),[reason,setReason]=useState('Front-desk correction');async function load(){const r=await apiFetch('/api/presence',{cache:'no-store'}),x=await r.json();r.ok?setData(x):setMessage(x.error)}useEffect(()=>{load();const t=setInterval(load,15000);return()=>clearInterval(t)},[]);async function act(action,extra={}){setMessage('Working…');const r=await apiFetch('/api/presence',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,reason,...extra})}),x=await r.json();setMessage(r.ok?'Presence updated.':x.error);if(r.ok)load()}
return <AppShell title="Live presence" subtitle="Who is here now, how long they have been here, employee coverage, and who comes in next" actions={<><button className="btn secondary" onClick={()=>act('reconcile')}><RefreshCw size={18}/>Run checkout policy</button><button className="btn danger" onClick={()=>act('check-out-all')}><LogOut size={18}/>Check out everyone</button></>}>
{message&&<div className={`inline-alert ${message==='Presence updated.'?'success':'error'}`}>{message}</div>}{!data?<LoadingState/>:<><section className="overview-strip"><div><UsersRound/><span><strong>{data.members.length}</strong> members</span></div><div><BriefcaseBusiness/><span><strong>{data.shifts.length}</strong> employees on clock</span></div><div><UserRoundCheck/><span><strong>{data.guests.length}</strong> guests</span></div><div><Clock3/><span><strong>{new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</strong> current time</span></div></section>
<section className="panel card-section"><div className="field-grid"><label className="field"><span>Reason recorded with manual corrections</span><input value={reason} onChange={e=>setReason(e.target.value)}/></label></div></section>
<section className="dashboard-grid"><article className="panel card-section"><div className="section-heading"><div><p className="eyebrow">Members</p><h2>Currently inside</h2></div></div>{data.members.length?<div className="presence-list">{data.members.map(row=><div key={row.id||row.personId}><span className="avatar-initial">{(row.displayName||'?')[0]}</span><div><strong>{row.displayName}</strong><small>Arrived {formatDateTime(row.checkedInAt)} · here {elapsed(row.checkedInAt)}</small></div><button className="btn tiny secondary" onClick={()=>act('check-out-member',{personId:row.personId})}><LogOut size={16}/>Check out</button></div>)}</div>:<EmptyState icon={UsersRound} title="No members inside" message="Member check-ins appear here immediately."/>}</article>
<article className="panel card-section"><div className="section-heading"><div><p className="eyebrow">Staff coverage</p><h2>Employees on the clock</h2></div><StatusPill tone={data.shifts.length?'green':'yellow'}>{data.shifts.length?'Covered':'No one clocked in'}</StatusPill></div>{data.shifts.length?<div className="presence-list">{data.shifts.map(row=><div key={row.id||row.personId}><span className="avatar-initial">{(row.displayName||'?')[0]}</span><div><strong>{row.displayName}</strong><small>Clocked in {formatDateTime(row.checkedInAt)} · {elapsed(row.checkedInAt)}</small></div><button className="btn tiny secondary" onClick={()=>act('clock-out-employee',{personId:row.personId})}><LogOut size={16}/>Clock out</button></div>)}</div>:<EmptyState icon={BriefcaseBusiness} title="No employees clocked in" message="Scheduled staff who are coming next are shown below."/>}</article>
<article className="panel card-section"><div className="section-heading"><div><p className="eyebrow">Guests</p><h2>Open guest visits</h2></div></div>{data.guests.length?<div className="presence-list">{data.guests.map(v=><div key={v.id}><span className="avatar-initial">{v.displayName?.[0]||'?'}</span><div><strong>{v.displayName}</strong><small>{v.hostName?`Host: ${v.hostName}`:`Checked in by: ${v.checkedInByName||'staff'}`} · {elapsed(v.checkInAt)}</small></div><button className="btn tiny secondary" onClick={()=>act('check-out-guest',{visitId:v.id})}><LogOut size={16}/>Check out</button></div>)}</div>:<EmptyState icon={UserRoundCheck} title="No guests inside" message="Guest check-ins appear here immediately."/>}</article>
<article className="panel card-section"><div className="section-heading"><div><p className="eyebrow">Next 24 hours</p><h2>Who is coming in next</h2></div><CalendarClock/></div>{data.nextStaff?.length?<div className="presence-list">{data.nextStaff.map(s=><div key={s.id}><span className="avatar-initial">{s.employeeName?.[0]||'?'}</span><div><strong>{s.employeeName}</strong><small>{formatDateTime(s.startsAt)} · {s.roleKey?.replaceAll('-',' ')}</small></div></div>)}</div>:<EmptyState icon={CalendarClock} title="No upcoming shifts" message="Published schedule assignments in the next 24 hours appear here."/>}</article></section></>}</AppShell>}
